### ISSUE TITLE
Add matrix on Node.js versions

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/solidity-template#1]
```yml
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '10', '12', '14', '16' ] 
        # This project supports all active/current Node.js versions at
        # https://nodejs.org/en/about/releases/
    name: Node ${{ matrix.node }} test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: npm run test
        env:
          FORCE_COLOR: 1
          ENABLE_GAS_REPORT: true
      - run: npm run test:inheritance
      - name: Print gas report
        run: cat gas-report.txt
```
